### ISSUE TITLE
Code to reproduce smooth latent visualization

### ISSUE THREAD

**Issue by ash2703** [yuval-alaluf/restyle-encoder#11]
Could you share the process for creating the visualization effects of iterative results

https://yuval-alaluf.github.io/restyle-encoder/images/toonify_gif.mp4

**Comment by yuval-alaluf** [comment]
Hi @ash2703 
I will be happy to share the script for creating the visualizations. Since I think this may be of interesting to others as well, I think it will be beneficial to organize the code in a notebook and upload the notebook here.  
I will be a bit busy in the next few days but hope to get to this by next week.

**Comment by Colliwomple** [comment]
> Hi @ash2703
> I will be happy to share the script for creating the visualizations. Since I think this may be of interesting to others as well, I think it will be beneficial to organize the code in a notebook and upload the notebook here.
> I will be a bit busy in the next few days but hope to get to this by next week.

This will be great ! Thank you !

**Comment by yuval-alaluf** [comment]
Hi all, I just uploaded the notebook for generating the animations. You can find the link to the Google Colab at the top of the README. I hope everything works fine. 
For now, I am closing this issue. However, if you find any issues/bugs with the notebook that I may have missed feel free to reopen :smile:
