### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

### ISSUE THREAD

**Issue by BrandoZhang** [yuval-alaluf/restyle-encoder#15]
When I tried to train ReStyle from a converted StyleGAN2 generator, I got:
```
Traceback (most recent call last):
  File "/restyle_encoder/scripts/train_restyle_psp.py", line 34, in <module>
    main()
  File "/restyle_encoder/scripts/train_restyle_psp.py", line 30, in main
    coach.train()
  File "/restyle_encoder/scripts/../training/coach_restyle_psp.py", line 140, in train
    y_hats, loss_dict, id_logs = self.perform_train_iteration_on_batch(x, y)
  File "/restyle_encoder/scripts/../training/coach_restyle_psp.py", line 125, in perform_train_iteration_on_batch
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by yuval-alaluf** [comment]
This occurs when you are trying to pass a variable multiple times through the graph without performing `loss.backward()`. Did you by any chance make any adjustments to the code? I see that the line numbers in your stack trace do not match the line numbers in the code.

**Comment by BrandoZhang** [comment]
Thanks @yuval-alaluf for quick reply.

Yes, I make some adjustments with this program, mainly on training logs (saving logs to a remote Tensorboard server). However, they are tested on original pSp's code.

Here are some modification I added without testing on pSp:
1. Dense sampling an avg_latent (see https://github.com/yuval-alaluf/restyle-encoder/issues/1#issuecomment-844179297):
```python
# in coach_restyle_psp.py 
# Initialize network		
self.net = pSp(self.opts).to(self.device)
if self.net.latent_avg is None:
    self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0]  # set a very large number for estimation
``` 
where index 0 returns a tensor that meets the dim requirements.

2. Sync with latest pSp's code:
Changed from

```python
# in coach_restyle_psp.py 
        if self.opts.moco_lambda > 0:
            self.moco_loss = moco_loss.MocoLoss()
```

to

```python
# in coach_restyle_psp.py 
        if self.opts.moco_lambda > 0:
            self.moco_loss = moco_loss.MocoLoss().to(self.device).eval()
```

Again, thanks for your nice work!

**Comment by yuval-alaluf** [comment]
Cool. The changes you made seem good from what I can tell. Seems like this needs some fun debugging to understand what's causing it in your case :) 
When I first implemented ReStyle I also came across this issue multiple times and the problem was solved by playing with using `.clone().detach().requires_grad_(True)` correctly.
Therefore, I think the area causing the problem is somewhere around here:
https://github.com/yuval-alaluf/restyle-encoder/blob/9088892689b3c90dd82b94922b4ee5a9d37875d0/training/coach_restyle_psp.py#L90-L98
However, you said yourself that you didn't change this portion of the code so I am a bit skeptical if this is the issue here. 🤔 

After you made your changes, did you try to see if you are able to train with StyleGAN generators I linked to the repo? I am wondering if the issue is somehow caused by your sampling of the latent average. If you are unable to recreate the issue with one of the StyleGANs [here](https://github.com/yuval-alaluf/restyle-encoder#auxiliary-models), I think your sampling portion of the code is causing the issue. If so, we can try understanding the difference between your 
```python
self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0]
``` 
and the latent average saved in the StyleGANs I provided.

By the way, I really like the idea of sampling many latents and averaging them. Does the corresponding image seem reasonable? If so, I may want to consider incorporating this into the repo if you are interested.

**Comment by BrandoZhang** [comment]
Wow, nice shot! 
I explicitly detach the `mean_latent` and everything goes well so far:
```python
self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0].detach()
```
I will create a PR when the training result is reasonable. Cheers!
