### ISSUE TITLE
Black & white image as input for FFHQ

### ISSUE THREAD

**Issue by joneidejohnsen** [yuval-alaluf/restyle-encoder#18]
Hi, Yuval – congratulations on a great paper! 👏

With the FFHQ model, I'm looking for a way to use a black & white image as input, and get a color image as the first average image from the StyleGAN generator. Similar to the technique used in the [Time Travel Rephotography paper (Luo et al. 2020)](https://time-travel-rephotography.github.io/).

Could you point me in the right direction on how to achieve this?

**Comment by yuval-alaluf** [comment]
Hi @joneidejohnsen 
Transforming a black and white image to a color version should definitely be possible. However, I didn't fully understand what you meant by "the first average image from the StyleGAN generator." Can you clarify what you mean here?

**Comment by joneidejohnsen** [comment]
My thought was that we can transform the B&W image to color in "Step 6: Perform Inference" in the Colab code, before we initialize the iterative refinement process.

More specifically, where we call `avg_image = get_avg_image(net)` to generate an image corresponding to the average latent code. In that way, a colorized "sibling" would be generated as a starting point for the inference.

**Comment by yuval-alaluf** [comment]
If I understand correctly, you are asking how you might be able to generate a colorized version of the image as the starting point for ReStyle? 

If so, one possible way is to generate paired data and train ReStyle to translate between the grayscale and colored version. 
Another option, which I am not sure will work, but will be easy to test is to encode the black and white image using the existing ReStyle encoder and perform style mixing with a different image on the fine level latents. This should change the color scheme of the black and white image. 

Let me know if I didn't understand correctly.

**Comment by joneidejohnsen** [comment]
Correct. And my initial thought was your second proposal – to use the existing ReStyle encoder and perform style mixing.

With the current code, this results in a black & white image very similar to the original, as the first generated image corresponding to the average latent code is almost without any colors:
![frida](https://user-images.githubusercontent.com/15170904/119314307-e63e4180-bc74-11eb-905a-e345e36df7f7.png)

Am I on the wrong track thinking it would be possible to ignore the color information – or in this case, lack of color information – when generating the first image corresponding to the average latent code?

**Comment by yuval-alaluf** [comment]
I think I understand now. It makes sense that in the example you showed, the output is nearly grayscale since ReStyle is trying to reconstruct the input exactly (including the color information). 
I dont think the average latent code is playing an important role here and changing it will probably not lead to a significant change in the result. 
If you want to convert the images from grayscale to color I think the easiest approach would be to simply train ReStyle to perform this translation. Then given a new grayscale image you should be able to generate a colored version. 

Just note, that when you say the first image corresponding to the average latent code, this is not entirely accurate. The first output's latent code is not the average code, but a different code. The average latent code corresponds to a different image unrelated to the input.

**Comment by joneidejohnsen** [comment]
I see – I'll experiment with both methods mentioned in https://github.com/yuval-alaluf/restyle-encoder/issues/18#issuecomment-846819818 and see where I get the best results.

And thanks for clearing up the difference between the average code and the first output's latent code. It makes sense as you get 5 output images when you have 5 inference steps.
