### ISSUE TITLE
How long for training?

### ISSUE THREAD

**Issue by di-mi-ta** [yuval-alaluf/restyle-encoder#20]
Hi, 

This work is interesting!

I wonder how long for training your models to reproduce the results in the paper?

Thanks!

**Comment by yuval-alaluf** [comment]
Hi @di-mi-ta ,
The number of training iterations varies between different domains and models (i.e., ReStyle-pSp and ReStyle-e4e), but to give you an idea, here are the number of iterations for the ReStyle-pSp models:

- Human faces (1024x1024 resolution): 110,000 iterations 
- Cars (512x384 resolution): 75,000 iterations 
- Animal faces (512x512 resolution): 40,000 iterations 
- Churches (256x256 resolution): 150,000 iterations 

These are the iterations that obtained the lowest losses during training for their respective domain. As you can see, the number of iterations varies vastly between the different domains due to their resolution and the difficulty of the domain.

**Comment by di-mi-ta** [comment]
Thank you for your reply!

**Comment by di-mi-ta** [comment]
Hi, 

Could you release the quantitative numbers you used to plot the diagrams for comparing your method with other methods in your paper! 
It would be better for reproducing correctly these diagrams if you release them! 

Thanks!

**Comment by yuval-alaluf** [comment]
This is a good idea. 
I have all the numbers saved somewhere but organizing them into clean, readable tables will take a bit of work. I will definitely consider adding this to the revision, but it may take a bit of time before I get to it. 
For the time being, I hope the diagrams are informative enough. However, if you have any issues or questions regarding the results, you are more than welcome to reach out.

**Comment by di-mi-ta** [comment]
Thank you for your quick reply. I hope to see them soon.
