### ISSUE TITLE
Error(s) in loading state_dict for Generator

### ISSUE THREAD

**Issue by LightingMc** [yuval-alaluf/restyle-encoder#29]
I downloaded the styleGAN-FFHQ weights and put them in the relevant folder "pretrained_models". However, I get the following error.
![image](https://user-images.githubusercontent.com/42900802/126697049-129b1ec6-bf32-4bc9-9f96-cd4b9924e76f.png)

**Comment by LightingMc** [comment]
I think it has got something to do with the output size. I got this error when I changed the output size to 256 from 1024.

**Comment by yuval-alaluf** [comment]
The `output_size` parameter defines the output resolution of your StyleGAN. Since the official FFHQ StyleGAN outputs images of size 1024x1024, you should set the `output_size` to 1024 rather than 256.
In any case, during training, the images are resized to 256x256 to speed up training and reduce memory consumption. During inference, you can choose whether to resize the outputs to 256x256 or keep them at the original 1024x1024 resolution.
