### ISSUE TITLE
how to train Encoder Bootstrapping?

### ISSUE THREAD

**Issue by YSL0226** [yuval-alaluf/restyle-encoder#30]
In Encoder Bootstrapping, you get latent vector by FFHQ encoder instead of the average toon image.
Could I know how to train Encoder Bootstrapping?
I only find Encoder Bootstrapping inference scrip.
Looking forward to your reply.

**Comment by yuval-alaluf** [comment]
There is actually no special script for encoder bootstrapping since this bootstrapping is only needed for inference.
All you need to do is train the two models separately as you would any encoder using the standard training script. 
And then you can pass the two trained encoders to the bootstrapping inference script.

**Comment by YSL0226** [comment]
Get it. Thank you for your reply.
