### ISSUE TITLE
Release the pretrained of original pSp model on Car, Horse, AFHQ Wild, Church in the paper

### ISSUE THREAD

**Issue by di-mi-ta** [yuval-alaluf/restyle-encoder#46]
Hi,

This work is very useful!

Could you release the pre-trained of the original pSp model on Car, Horse, AFHQ Wild, Church reported in the main paper? 

Thanks!

**Comment by yuval-alaluf** [comment]
I apologize for the delay. I haven't had the time to prepare everything.  I hope it's still relevant. 
I have uploaded the 4 pSp models to the following Google Drive link: 

https://drive.google.com/drive/folders/1-7DJzHlzzFqnD3frBhPlEipfbiH9tBPq?usp=sharing

I have also provided the encoder class that was used to train these models. 
As I mentioned before, there is no guarantee that these checkpoints will work with the code since they were trained a while back.
