### ISSUE TITLE
GradualStyleEncoder

### ISSUE THREAD

**Issue by gzhhhere** [yuval-alaluf/restyle-encoder#54]
Hi!
Theoretically，GradualStyleEncoder in PSP is better than BackboneEncoder, have you tried the GradualStyleEncoder?

**Comment by yuval-alaluf** [comment]
In the Appendix we provide an ablation study to demonstrate that the more complex GradualStyleEncoder is not necessary with ReStyle due to the iterations used with ReStyle. In other words, since we can take a couple of steps to perform the final inversion, we can get equal performance with a smaller network.

**Comment by gzhhhere** [comment]
> In the Appendix we provide an ablation study to demonstrate that the more complex GradualStyleEncoder is not necessary with ReStyle due to the iterations used with ReStyle. In other words, since we can take a couple of steps to perform the final inversion, we can get equal performance with a smaller network.

i got it, thank you!

**Comment by gzhhhere** [comment]
> In the Appendix we provide an ablation study to demonstrate that the more complex GradualStyleEncoder is not necessary with ReStyle due to the iterations used with ReStyle. In other words, since we can take a couple of steps to perform the final inversion, we can get equal performance with a smaller network.

i got it, thank you!
