### ISSUE TITLE
Improving toonification result

### ISSUE THREAD

**Issue by Nerdyvedi** [yuval-alaluf/restyle-encoder#6]
Hi, 
I was wondering what can we do to improve the toonification result. I tested with Encoder Bootstrapping method, Using the following command :
`python scripts/encoder_bootstrapping_inference.py --exp_dir=./toonify --model_1_checkpoint_path=./pretrained/restyle_psp_ffhq_encode.pt --model_2_checkpoint_path=./pretrained/restyle_psp_toonify.pt --data_path=./test/test_A --test_batch_size=1 --test_workers=1 --n_iters_per_batch=1`

I get decent results, But would like to make it look more like the input image.

A sample of result I am getting.

![emma_stone](https://user-images.githubusercontent.com/23276664/114444409-7b690780-9bec-11eb-9d47-4ad933c70b80.png)

**Comment by yuval-alaluf** [comment]
Hi @Nerdyvedi ,
If you want the output to look more like the input image, you can try adding more inference steps by increasing `n_iters_per_batch`.  
For example, if you take a look at the [images linked in the README](https://github.com/yuval-alaluf/restyle-encoder#encoder-bootstrapping), you can see that each additional step moves the output closer to the input image (e.g., adding facial hair, changing head shape, etc).

**Comment by Nerdyvedi** [comment]
Thanks @yuval-alaluf 
I increased n_iters_per_batch to 5.
Result keeps looking worse :)

![Uploading emma_stone.png…]()

**Comment by yuval-alaluf** [comment]
I would say the later results seem more like the original input, which is what you wanted. For example, you can see that the eyes and head shape change to be more like the input. 
In my opinion, however, when performing toonification, you do want to see changes between the input and output images. For example, I like how the first result has big eyes, which I think is a nice feature here. 
You can see that its not perfect though. For example, the encoder tries to add an outline of a shirt that isn't there in the input. 
Overall though, I think the results are reasonable. If I may, what other aspects of the results do you find poor?

**Comment by Vedanta-Z** [comment]
@yuval-alaluf , I am aiming to have an output like this.
Could you guide me what changes I should make to the model to get an output like this.
![photo5798812157704517461](https://user-images.githubusercontent.com/72018835/114576033-647fef00-9c98-11eb-987f-fbe56b523eed.jpg)

**Comment by yuval-alaluf** [comment]
I am unsure where you got the above output (I assume you got it using some other method).  
On this particular input, it seems like the image you attached above is better than the one generated by ReStyle. 
On some inputs, ReStyle may perform better than other methods and on other inputs, it may perform worse. It appears that on this particular input, ReStyle simply performs worse. 
Does that make sense?

**Comment by Nerdyvedi** [comment]
Okay, Makes sense.
Actually the output is using https://github.com/eladrich/pixel2style2pixel 
Are there some hyperparameters I could change, To get a result like this. 
![photo5798812157704517461](https://user-images.githubusercontent.com/23276664/114579968-081ece80-9c9c-11eb-82c7-03f309cccbdc.jpg)

**Comment by yuval-alaluf** [comment]
There aren't really any parameters in inference that I can think of that will change the result. 
Since the result you got above was from pSp, what you could try doing is replacing the `restyle_psp_ffhq_encode.pt` model that is used to initialize the encoder bootstrapping with the `psp_ffhq_encode.pt` model that is used in pSp. 
My thinking here is that if we use a different initialization for the bootstrapping, we may get different results. I am not entirely sure if this will change anything, but it is interesting to see. 

Note that the current code does not support the change above. However, it is easy to support it. 
Currently, the initialization is performed using the follow: 
https://github.com/yuval-alaluf/restyle-encoder/blob/c6453b216ee48afe247ea042fe307dfc82a10d92/scripts/encoder_bootstrapping_inference.py#L120-L127

I believe that all you need to do is change the above lines to: 
```python
y_hat, latent = net1.forward(inputs, randomize_noise=False, return_latents=True, resize=opts.resize_outputs)
```
where now `net1` is the pSp encoder. 
Let me know if something above doesn't make sense.

**Comment by Nerdyvedi** [comment]
@yuval-alaluf 
Made the changes . Getting the following error
  File "./models/psp.py", line 19, in __init__
    self.n_styles = int(math.log(self.opts.output_size, 2)) * 2 - 2
AttributeError: 'Namespace' object has no attribute 'output_size'

**Comment by yuval-alaluf** [comment]
When we load the model we have the following lines: 
https://github.com/yuval-alaluf/restyle-encoder/blob/c6453b216ee48afe247ea042fe307dfc82a10d92/scripts/encoder_bootstrapping_inference.py#L31-L36

Before line 36, try adding:
```python
if 'output_size' not in opts:
    opts['output_size'] = 1024
```
and let me know what you get. There may be some other small changes needed :)

**Comment by Nerdyvedi** [comment]
@yuval-alaluf Okay, now it is able to load the checkpoints. But getting size mismatch error.

`size mismatch for input_layer.0.weight: copying a param with shape torch.Size([64, 6, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).`

**Comment by yuval-alaluf** [comment]
Ok this makes sense because pSp uses `input_nc` of 3 and restyle uses 6. You should play around with how you load net1 and net2 and try to match the parameters accordingly. 
I apologize, but I will need to come back to this at a later time. If you wish, you can continue playing with it or wait a bit and hopefully I can come back to this soon.

**Comment by yuval-alaluf** [comment]
I had a few minutes to play around with the code and I was able to make the changes. Since this is a quick hack, I'll upload the file here so you can take a look. We were pretty much missing one line of code. 
I was curious how initializing with pSp would change the result, so I ran it on your input. Here is the result: 
![stone](https://user-images.githubusercontent.com/37438467/114602805-b37d5280-9c9f-11eb-9cfe-53024d426f71.jpg)

I hope the results are more what you're looking for (the middle image is the toonified result). I'd say that this looks better than what ReStyle came up with so it's nice to see that a small change can lead to some improvements on particular inputs. The result is similar to what pSp returned, but I think the results here are more colorful.

Here is the code:
[encoder_bootstrap_with_psp.txt](https://github.com/yuval-alaluf/restyle-encoder/files/6305915/encoder_bootstrap_with_psp.txt)

**Comment by qo4on** [comment]
Hi, @yuval-alaluf !
I tried your script and had some errors in `run_on_batch` function at `net1.forward` call. Do you know what's the problem?
```
!python scripts/encoder_bootstrap_with_psp.py \
--exp_dir=toonify \
--model_1_checkpoint_path=pretrained_models/restyle_psp_ffhq_encode.pt \
--model_2_checkpoint_path=pretrained_models/restyle_psp_toonify.pt \
--data_path=$save_path_vm \
--test_batch_size=1 \
--test_workers=1 \
--n_iters_per_batch=1

Loading ReStyle pSp from checkpoint: pretrained_models/restyle_psp_ffhq_encode.pt
Loading ReStyle pSp from checkpoint: pretrained_models/restyle_psp_toonify.pt
Loading dataset for ffhq_encode
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/encoder_bootstrap_with_psp.py", line 158, in <module>
    run()
  File "scripts/encoder_bootstrap_with_psp.py", line 92, in run
    result_batch = run_on_batch(input_cuda, net1, net2, opts, avg_image)
  File "scripts/encoder_bootstrap_with_psp.py", line 137, in run_on_batch
    resize=opts.resize_outputs)
  File "./models/psp.py", line 60, in forward
    codes = self.encoder(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "./models/encoders/restyle_psp_encoders.py", line 44, in forward
    x = self.input_layer(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 6, 3, 3], expected input[1, 3, 256, 256] to have 6 channels, but got 3 channels instead
```
```
def run_on_batch(inputs, net1, net2, opts, avg_image):
    y_hat, latent = None, None
    results_batch = {idx: [] for idx in range(inputs.shape[0])}

    # initialize using the first net
    # avg_image_for_batch = avg_image.unsqueeze(0).repeat(inputs.shape[0], 1, 1, 1)
    # x_input = torch.cat([inputs, avg_image_for_batch], dim=1)
    # y_hat, latent = net1.forward(x_input,
    #                              latent=latent,
    #                              randomize_noise=False,
    #                              return_latents=True,
    #                              resize=opts.resize_outputs)
    y_hat, latent = net1.forward(inputs,
                                 randomize_noise=False,
                                 return_latents=True,
                                 resize=opts.resize_outputs)
    for idx in range(inputs.shape[0]):
        results_batch[idx].append(y_hat[idx])
    y_hat = net1.face_pool(y_hat)

    # iteratively translate using the resulting latent and generated image
    for iter in range(opts.n_iters_per_batch):
        x_input = torch.cat([inputs, y_hat], dim=1)
        y_hat, latent = net2.forward(x_input,
                                     latent=latent,
                                     randomize_noise=False,
                                     return_latents=True,
                                     resize=opts.resize_outputs)
        for idx in range(inputs.shape[0]):
            results_batch[idx].append(y_hat[idx])
        y_hat = net1.face_pool(y_hat)

    return results_batch
```

**Comment by qo4on** [comment]
Ooh, sorry! I forgot to change the model to `pSp`. Everything works perfectly!

**Comment by qo4on** [comment]
> (the middle image is the toonified result). I'd say that this looks better than what ReStyle came up with

I think it depends on the input. I tried psp (`psp_ffhq_toonify`), restyle (`restyle_psp_ffhq_encode, restyle_psp_toonify`) and restyle with psp (`psp_ffhq_encode, restyle_psp_toonify`) on the same input. psp and restyle with psp sometimes generate horrible results. Most often restyle does better but it has a reddish spot that leads to different eyes colors. Does anybody know a better solution for face toonification?
![image](https://user-images.githubusercontent.com/35609308/128086900-1acba5c9-9e61-486d-89d5-e8b360ce9961.png)
