### ISSUE TITLE
bad results 

### ISSUE THREAD

**Issue by Jimzhou82sub** [yuval-alaluf/restyle-encoder#61]
Could you help me ?
![1](https://user-images.githubusercontent.com/40049148/150972240-de914a66-393d-45d7-a799-d9af1f1fa69f.jpg)

**Comment by MartFire** [comment]
I think the model expects aligned images.
I'm not sure if the model is overfitted on FFHQ or it needs very high-resolution images as input (1024x1024) but apart from images from FFHQ (the model trained on these images), all the reconstructions were quite poor when I tried other datasets. Plus the additional steps make it worse, the network tries to reduce the pixel loss but the face doesn't look human anymore.[](url
![3023909862_1](https://user-images.githubusercontent.com/15039429/151410031-2e7f8f25-74aa-48e5-8e32-cfcfa343daa5.jpg)
)

**Comment by Jimzhou82sub** [comment]
Ok, I got it, thanx a lot, best wishes for you

**Comment by yuval-alaluf** [comment]
All the results posted above are unaligned and are therefore out of distribution to what the *StyleGAN* generator can generate. Please align all your faces before passing them to the encoder. 

> I'm not sure if the model is overfitted on FFHQ or it needs very high-resolution images as input (1024x1024) but apart from images from FFHQ (the model trained on these images), all the reconstructions were quite poor when I tried other datasets.

I think this conclusion is a bit misleading. The model is not overfitted to FFHQ since it also achieves very good reconstructions on images from other datasets (e.g., CelebA-HQ) and images in the wild (e.g., the images shown in the repo [here](https://github.com/yuval-alaluf/restyle-encoder#editing). 
The input also does not need to be high resolution (1024x1024). The encoder itself was trained on 256x256 images from FFHQ so there is not need for inputs to be at such a high resolution. In fact, the inputs can be 256x256 while the outputs will be 1024x1024, so in some cases, the encoder can actually improve the resolution of the input image. 

All this is to say that when working on faces and StyleGAN2, l the inputs must be aligned before passing them to the encoder.

**Comment by Jimzhou82sub** [comment]
I  rotated the picture and get a good result, pretty job !  Speaking from  my  experience,  I think the photo's length-width ratio plays a pretty important role.
