### ISSUE TITLE
Passing of label during Image Inference

### ISSUE THREAD

**Issue by rut00** [yuval-alaluf/restyle-encoder#79]
Is it possible to pass the label while we infer the image using an encoder? Here encoder is trained using a labeled dataset and network. If you can share some ideas for changes to be done.

Thank you.

**Comment by richa0404** [comment]
Hello @rut00, Did you find a solution to the issue? I also have an encoder trained over a labeled dataset and StyleGAN network.

Also, I observed that the avg_image generated each time respects only one label.

@yuval-alaluf  Can you please help me out regarding the issue?

**Comment by yuval-alaluf** [comment]
I am not sure the motivation for using an encoder trained on labeled data in order to find the latent for representing an image. These are two seemingly different tasks. Maybe the encoder trained on labeled data can give better embeddings if you're trying to embed multiple classes into the same latent space, but even then, I am not sure if you will see much of a difference. 
Could you provide some more details on exactly why you want to use labeled data here?

**Comment by rut00** [comment]
We want inferred images to be generated with the label we pass. In the case of a generator trained over a labeled dataset, generated images have the same label that we pass but in the case of an encoder, it always infers the image with the label that the average image has. So how to tell the encoder to use different labels?

**Comment by yuval-alaluf** [comment]
You will need to train something yourself. I am not sure how I would go about this, and it seems like you will need to think of some modifications yourself in order to get something like this to work. So unfortunately, you're on your own here.
